### ISSUE TITLE
xplayer esx_addonaccount

### ISSUE THREAD

**Issue by Fluxiitis** [ESX-Org/esx_addonaccount#14]
Error running system event handling function for resource esx_addonaccount: citizen:/scripting/lua/scheduler.lua
:41: Failed to execute thread: server/main.lua:71: attempt to index a nil value (local 'xPlayer')
stack traceback:
        server/main.lua:71: in upvalue 'handler'
        citizen:/scripting/lua/scheduler.lua:195: in function <citizen:/scripting/lua/scheduler.lua:194>
stack traceback:
        [C]: in function 'error'
        citizen:/scripting/lua/scheduler.lua:41: in field 'CreateThreadNow'
        citizen:/scripting/lua/scheduler.lua:194: in function <citizen:/scripting/lua/scheduler.lua:158>

**Comment by mareckithc** [comment]
Error running system event handling function for resource esx_addonaccount: citizen:/scripting/lua/scheduler.lua:41: Failed to execute thread: @esx_addonaccount/server/main.lua:71: attempt to index a nil value (local 'xPlayer')
stack traceback:
        @esx_addonaccount/server/main.lua:71: in upvalue 'handler'
        citizen:/scripting/lua/scheduler.lua:219: in function <citizen:/scripting/lua/scheduler.lua:218>
stack traceback:
        [C]: in function 'error'
        citizen:/scripting/lua/scheduler.lua:41: in field 'CreateThreadNow'
        citizen:/scripting/lua/scheduler.lua:218: in function <citizen:/scripting/lua/scheduler.lua:182>
