### ISSUE TITLE
Console Error server/main.lua:87: attempt to index a nil value (local 'xPlayer')

### ISSUE THREAD

**Issue by MtotheC1987** [ESX-Org/esx_addonaccount#19]
Fresh install and reinstall but keeping this error :

SCRIPT ERROR: @esx_addonaccount/server/main.lua:87: attempt to index a nil value (local 'xPlayer')
> cb (@es_extended/server/main.lua:215)
> ref (@es_extended/server/classes/player.lua:234)
> setImmediate (@mysql-async/mysql-async.js:14431)

Config File from FiveM self:

# These resources will start by default.
ensure mapmanager
ensure chat
ensure spawnmanager
ensure sessionmanager
ensure fivem
ensure hardcap
ensure rconlog
ensure scoreboard

###################### Set connection MYSQL-async
set mysql_connection_string "server=localhost;uid=.....;password=.......;database=........"

###################### Disable Couchdb from essentialmode
set es_enableCustomData 1

###################### libs
start mysql-async

add_ace resource.essentialmode command.sets allow
add_ace resource.essentialmode command.add_principal allow
add_ace resource.essentialmode command.add_ace allow
start essentialmode
start es_admin2
start esplugin_mysql
start es_extended

###################### esx
start cron
start esx_menu_default
start esx_menu_list
start esx_menu_dialog
start esx_addonaccount

**Comment by oMadMartigaNo** [comment]
I have almost the same error.

`SCRIPT ERROR: @esx_addonaccount/server/main.lua:71: attempt to index a nil value (local 'xPlayer')`
`> cb (@es_extended/server/main.lua:215)`
`> ref (@es_extended/server/classes/player.lua:234)`
`> setImmediate (@mysql-async/mysql-async.js:14431)`

 # server.cfg
>     endpoint_add_tcp "0.0.0.0:30120"
>     endpoint_add_udp "0.0.0.0:30120"
> 
>     set mysql_connection_string "server=x.x.x.x;database=xxxx;userid=xxxx;password=xxxx"
>     set es_enableCustomData 1
>     set sv_licenseKey "xxxx"
>     sv_scriptHookAllowed 0
>     rcon_password "xxxx"
>     sv_hostname "xxxx"
>     set temp_convar "xxxx"
> 
> # disable announcing? clear out the master by uncommenting this
>     sv_master1 ""
> 
> # want to only allow players authenticated with a third-party provider like Steam?
>     sv_authMaxVariance 1
>     sv_authMinTrust 1
> 
> # add system admins
>     add_ace group.admin command allow # allow all commands
>     add_ace group.admin command.quit deny # but don't allow quit
>     add_ace resource.essentialmode command.add_ace allow
>     add_ace resource.essentialmode command.add_principal allow
>     add_principal identifier.steam:xxxx group.admin # add the admin to the group
> 
> # hide player endpoints in external log output
>     sv_endpointprivacy true
> 
> #### FIVEM DEFAULT ####
>     start mapmanager
>     start chat
>     start spawnmanager
>     start sessionmanager
>     restart sessionmanager
>     start fivem
>     start hardcap
>     start rconlog
>     start scoreboard
>     start baseevents
> 
> #### MYSQL ASYNC
>     start mysql-async
> 
> #### ESSENTIAL MODS
>     start essentialmode
>     start esplugin_mysql
>     start es_admin2
>     start es_extended
> 
> #### ESX REQUIRED MODS
>     start instance
>     start cron
>     start skinchanger
>     start esx_skin
>     start esx_menu_default
>     start esx_menu_list
>     start esx_menu_dialog
>     start esx_phone
>     start esx_addonaccount
>     start esx_addoninventory
>     start esx_datastore
>     start esx_society
>     start esx_service
>     start esx_billing
> 
> #### ESX JOBS
>     start esx_jobs
>     start esx_joblisting
>     start esx_taxijob
>     start esx_mechanicjob
>     start esx_policejob
>     start esx_property
>     start esx_realestateagentjob
>     start esx_bankerjob
>     start esx_ambulancejob
>     start esx_vehicleshop
>     start esx_shops
> 
> #### ESX ANY OTHER MODS
>     start esx_status
>     start esx_basicneeds
>     start esx_clotheshop
>     start esx_garage
>     start esx_holdup
>     start esx_drugs
>     start esx_atm
>     start esx_identity
>     start esx_license
>     start esx_boat
>     start esx_accessories
>     start esx_animations
>     start esx_menu_list
>     start esx_weaponshop
>     start esx_barbershop
>     start esx_menu_default
>     start esx_menu_dialog
>     # start esx_whitelist
>     start esx_lscustom
>     start esx_slots
> 
> #### ANY NON ESX MODS
>     #start nonESXmod
>     start skinchanger
>     start target
>     start menu
>     start pNotify
>     start 99kr-shops
>     start esx_eden_clotheshop

**Comment by CALauer** [comment]
I have the exact same error
set mysql_debug 1
set mysql_debug_output "console"
set mysql_slow_query_warning 200

#default
ensure mapmanager
ensure chat
ensure spawnmanager
ensure sessionmanager
ensure fivem
ensure hardcap
ensure rconlog
ensure scoreboard

start keks
# My Downloaded Scripts
start mysql-async
start essentialmode
start esplugin_mysql
start es_extended
start esx_menu_default
start esx_menu_list
start esx_menu_dialog
#my added reources
start skinchanger #no dependencies/requirements 
start esx_skin #requirements - esx skinchanger
start esx_billing #no dependencies/requirements 
start cron  #no dependencies
start esx_addonaccount #no dependencies/requirements 
start esx_addoninventory
start esx_society # requirements cron and esc_addonaccount
start esx_datastore #no dependencies/requirements 
#start esx_admin
start esx_license #no dependencies/requirements 
start esx_policejob #requirements esx_billing esx_society esx_datastore esx_identity esx_license
start esx_identity #requirements esx_skin esx_police esx_society

**Comment by nunoantunes-github** [comment]
someone solve this? i have the same error

**Comment by Trickxqster** [comment]
### **Fix: (bottom of server/main.lua - line 66-88)**


```
AddEventHandler('esx:playerLoaded', function(playerId, xPlayer)

	local xPlayer       = ESX.GetPlayerFromId(source)
	local addonAccounts = {}

	for i=1, #AccountsIndex, 1 do
		local name    = AccountsIndex[i]
		local account = GetAccount(name, xPlayer.identifier)

		if account == nil then
			MySQL.Async.execute('INSERT INTO addon_account_data (account_name, money, owner) VALUES (@account_name, @money, @owner)', {
				['@account_name'] = name,
				['@money']        = 0,
				['@owner']        = xPlayer.identifier
			})

			account = CreateAddonAccount(name, xPlayer.identifier, 0)
			table.insert(Accounts[name], account)
		end

		table.insert(addonAccounts, account)
	end

	xPlayer.set('addonAccounts', addonAccounts)
end)
```

**Comment by Danvm94** [comment]
Same error here, anyone have fixed that?

SCRIPT ERROR: @esx_addonaccount/server/main.lua:87: attempt to index a nil value (local 'xPlayer')

SCRIPT ERROR: @esx_addonaccount/server/main.lua:47: attempt to get length of a nil value (field '?')

**Comment by TMarcccci** [comment]
I have this errors too.

All time with every script randomly. Error with (local xPlayer)

Help me please!

**Comment by CecemelDev** [comment]
Same problem with ESX_SHOPS
`SCRIPT ERROR: @esx_shops/server/main.lua:60: attempt to call a nil value (field 'canCarryItem')`

**Comment by SienkoV2** [comment]
Did you have resolved this :( ?

**Comment by vejniik** [comment]
fix anybody? =))

**Comment by czsquizer** [comment]
For the canCarryItem it is caused your es_extended does not support weight system and it does support Limit System

**Comment by prouargegamer** [comment]
which esx_extended version to choose?

**Comment by Drachenlordaltschauerberg** [comment]
Did anyone Fixed it i have exactly the same eror
