### ISSUE TITLE
Error when trying to interact with boss menu

### ISSUE THREAD

**Issue by whitewolftbc** [ESX-Org/esx_addonaccount#4]
Hi,
I had a problem
When i go to the police boss menu,open it and select to deposit money,im entering for example $5000
and then i click to deposit them it says You have deposited $5000 but the money doesnt appear in the society.
When i open the console the following error appears:
`Error running system event handling function for resource esx_addonaccount: citizen:/scripting/lua/scheduler.lua:41: Failed to execute thread: server/main.lua:77: attempt to call a nil value (local 'cb') stack traceback: server/main.lua:77: in upvalue 'handler'`

Which line 77 is 
AddEventHandler('esx_addonaccount:getSharedAccount', function(name, cb)
	cb(GetSharedAccount(name))
end)
and to be correctly line 77 is exactly  cb(GetSharedAccount(name))
so i guess the issue is in that 'cb' ?!?
what does cb means ? 
with this error it cannot add the money to the society and remove my money
any suggestions ? 
sorry for my bad english

Best regards

**Comment by SupremeBeardlife** [comment]
cb = callback. I guess you haven't configured the scripts correctly. Check the main.lua file and see what it says on the lines where it Triggers events and compare it to the esx_addonaccount usage part

**Comment by Dragese** [comment]
Same issuse. 
With cb. Help please

**Comment by Sidusol** [comment]
I have problem that there is no informaction after I try to deposit money on society account... I doesn't take money from me and it doesn't deposit... Just nothing happens

**Comment by Dragese** [comment]
remember guys of requsted resources

**Comment by Sidusol** [comment]
all resources installed

**Comment by ElPumpo** [comment]
You have not registered the account in db

**Comment by bbigelli** [comment]
esx_society: steam: xxx  attempted open a society boss menu!

i've this issue someone know how to fix?
