### ISSUE TITLE
Getting this error...

### ISSUE THREAD

**Issue by saemarp** [ESX-Org/esx_addonaccount#5]
Error running system event handling function for resource esx_addonaccount: citizen:/scripting/lua/scheduler.lua:41: Failed to execute thread: server/main.lua:61: attempt to get length of a nil value (field '?')
stack traceback:
        server/main.lua:61: in function 'GetAccount'
        server/main.lua:73: in upvalue 'handler'
        citizen:/scripting/lua/scheduler.lua:175: in function citizen:/scripting/lua/scheduler.lua:174
stack traceback:
        [C]: in function 'error'
        citizen:/scripting/lua/scheduler.lua:41: in field 'CreateThreadNow'
        citizen:/scripting/lua/scheduler.lua:174: in function citizen:/scripting/lua/scheduler.lua:138

I ran it through a couple of lua parsers to check the code and they both say line six is an issue:

TriggerEvent('esx:getSharedObject', function(obj) ESX = obj end)

Any help would be appreciated.

**Comment by dracuslayer** [comment]
I am getting this error as well.
`function GetAccount(name, owner)
	for i=1, #Accounts[name], 1 do
		if Accounts[name][i].owner == owner then
			return Accounts[name][i]
		end
	end
end`

**Comment by ElPumpo** [comment]
You have not registered the account in db

**Comment by Prognoizes** [comment]
What account you talk about? because i get this error as well. All works but i get this error so there is something wrong and i like to know what that is.. Thanks in advanced
